# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Cloudtips-SDK-iOS-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CloudtipsSDK', :path => "../"
#  pod 'CloudtipsSDK', :git => "https://github.com/cloudpayments/CloudTips-SDK-iOS", :branch => "master"

end

post_install do |pi|
  pi.pods_project.targets.each do |t|

    if t.respond_to?(:product_type) and t.product_type == "com.apple.product-type.bundle"
      t.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
    
  end
end

